meta:
  # Min Ergogen version for KiCad 8 footprints
  engine: 4.1.0
units:
  # Proxy spacing variables, choc spacing
  kx: cx
  ky: cy

  # For the preview at https://ergogen.ceoloide.com/
  $default_width: cx
  $default_height: cy

  # Switch padding, i.e. distance from center of switch (Point) to 
  # the nearest edge of the PCB. Essentially a 1mm pad. Useful
  # for adjustment operations in relation to a Point.
  cpx: 1 + kx / 2
  cpy: 1 + ky / 2

  # Controller dimensions
  nice_nano_length: 34.1
  nice_nano_width: 18.3
points:
  zones:
    matrix:
      anchor:
        # Cancel out rotations from column splay
        rotate: 6
      key:
        padding: ky
        spread: kx
      columns:
        pinky:
        ring:
          key:
            splay: -3
            spread: kx + 0.5
            stagger: ky - 2
        middle:
          key:
            splay: -3
            spread: kx + 0.5
            stagger: 3
        pointer:
          key:
            stagger: -6
        inner:
          key:
            stagger: -2
      rows:
        bottom:
        middle:
        top:
    thumbs:
      anchor:
        ref: matrix_pointer_bottom
        shift: [4, -24]
      key:
        padding: 1ky
        spread: 1kx
      columns:
        tucky:
        middle:
          key:
            shift: [2.4, -1.8]
            splay: -13
        reachy:
          key:
            shift: [5.1, -3.2]
            splay: -13
      rows:
        cluster:
  mirror:
    ref: thumbs_reachy_cluster
    distance: 2kx
outlines:
  # Shows the keycaps
  _keycaps:
    - what: rectangle
      where: true
      size: [kx, ky]
  _switch_holes:
    - what: rectangle
      where: true
      size: [14, 14]
  _matrix:
    - what: rectangle
      where: /^matrix_/
      size: [kx, ky]
      expand: 1
  _thumbs:
    - what: rectangle
      where: /^thumbs_/
      size: [kx, ky]
      expand: 1
  # Connect the thumbs to the matrix
  _matrix_thumb_connector:
    - what: polygon
      points:
        - ref: thumbs_tucky_cluster
          shift: [-1cpx - 0, 2cpy]
        - ref: matrix_inner_bottom
          shift: [1cpx, 1cpy]
        - ref: matrix_inner_bottom
          shift: [1cpx, -3cpy]
        - ref: thumbs_tucky_cluster
          shift: [-1cpx - 0, 0]
  # Fix the splay gap between thumbs.
  _thumb_bandaid:
    - what: polygon
      points:
        - ref: thumbs_middle_cluster
          shift: [1cpx, 1cpy]
        - ref: thumbs_reachy_cluster
          shift: [-1cpx, 1cpy]
        - ref: thumbs_middle_cluster
          shift: [1cpx, -1cpy]
        - ref: thumbs_reachy_cluster
          shift: [-1cpx, -1cpy]
  # Fix the splay gap between ring and middle fingers
  _matrix_bandaid:
    - what: polygon
      points:
        - ref: matrix_ring_top
          shift: [0cpx, 1cpy]
        - ref: matrix_ring_top
          shift: [2cpx, 1cpy]
        - ref: matrix_ring_top
          shift: [2cpx, -1cpy]
        - ref: matrix_ring_top
          shift: [1cpx, -1cpy]
  _controller:
    - what: polygon
      adjust: 
        ref: matrix_inner_bottom
        shift: [1cpx + 3, -1cpx + 1]
      points:
        - shift: [0, 0]
        - shift: [0, nice_nano_length]
        - shift: [nice_nano_width, 0]
        - shift: [0, -nice_nano_length]
  _controller_area:
    - what: polygon
      adjust:
        ref: matrix_inner_bottom
        shift: [0, -2cpy]
      points:
        - shift: [0, 0]
        - shift: [0, 1cpy + 0.5]
        - shift: [0, nice_nano_length]
        - shift: [1cpx + 2, 0]
        - shift: [nice_nano_width + 1, 0]
        - shift: [0, -nice_nano_length]
        - shift: [0, -2cpy - 2]
  _battery:
    # 12 x 30, small one from typeractive
    - what: polygon
      adjust:
        ref: matrix_ring_bottom
        shift: [-1cpx + 4.5, -1cpy - 23]
        rotate: -2
      points:
        - shift: [0, 0]
        - shift: [30, 0]
        - shift: [0, 20]
        - shift: [-30, 0]
  _jst:
    # 8 x 4.5
    - what: polygon
      adjust:
        ref: matrix_pinky_bottom
        shift: [-5, -1cpy - 7]
      points:
        - shift: [0, 0]
        - shift: [8, 0]
        - shift: [0, 4.5]
        - shift: [-8, 0]
  # Fills out bottom corner from pink to thumb cluster.
  # Makes a space for the JST connector
  _bottom_left:
    - what: polygon
      points:
        - ref: matrix_pinky_bottom
          shift: [-1cpx, 1cpy]
        - shift: [70, 0]
        - ref: thumbs_tucky_cluster
          shift: [0cpx, -1cpy]
        - shift: [-65, 0]
        - ref: matrix_pinky_bottom
          shift: [-1cpx, -17]
  _debug_rectangle:
    - what: polygon
      points:
        - shift: [-80, 130]
        - shift: [250, 0]
        - shift: [0, -230]
        - shift: [-250, 0]
  left_board:
    - name: _matrix
    - name: _thumbs
    - name: _matrix_thumb_connector
    - name: _thumb_bandaid
    - name: _matrix_bandaid
    - name: _controller_area
    - name: _controller
    - name: _bottom_left
    - name: _debug_rectangle
  switch_plate:
    - name: left_board
    - operation: subtract
      name: _switch_holes
  preview:
    - name: left_board
    - name: _keycaps
      operation: subtract
    - name: _battery
      operation: subtract
    - name: _jst
      operation: subtract
    - name: _controller
      operation: subtract
pcbs:
  left:
    # Required, since footprints are KiCad 8 only
    template: kicad8
    outlines:
      main:
        outline: left_board
    footprints:
      choc_hotswap:
        what: ceoloide/switch_choc_v1_v2
        where: true
        params:
          choc_v2_support: false
          keycap_height: ky
          keycap_width: kx
          # hotswap_3dmodel_filename: 3dmodels/ScottoKeebs_Hotswap.3dshapes/Choc_V1.step
          # switch_3dmodel_filename: 3dmodels/ScottoKeebs_Choc.3dshapes/Choc_V1.step
          # TODO: These are certainly broken
          from: "{{name}}_from"
          to: "{{name}}_to"
      nice_nano:
        what: ceoloide/mcu_nice_nano
        params:
          # mcu_3dmodel_filename: 3dmodels/ScottoKeebs_MCU.3dshapes/Nice_Nano_V2.step
          # mcu_3dmodel_xyz_offset: [0, 0, 3]
        where:
          # Align the bottom of the nice nano with the bottom keycap
          ref: matrix_inner_bottom
          shift: [1kx + 3, nice_nano_length / 2 - kx / 2]
          rotate: 0
      reset_switch:
        what: ceoloide/reset_switch_smd_side
        # top right, near the USB port
        where: 
          ref: matrix_inner_top
          shift: [0, cy + 3]
      power_switch:
        what: ceoloide/power_switch_smd_side
        # top left
        where:
          ref: matrix_ring_top
          shift: [0, cy + 3]
      battery_connector:
        what: ceoloide/battery_connector_jst_ph_2
        where:
          ref: thumbs_tucky_cluster
          shift: [-1cpx - 4, -1cpy + 2]
      # TODO: battery outline
      # TODO: speaker?
      # TODO: haptic?
      # TODO: LED?
