meta:
  # Min Ergogen version for KiCad 8 footprints
  engine: 4.1.0
units:
  # Proxy spacing variables, choc spacing
  kx: cx
  ky: cy

  # For the preview at https://ergogen.ceoloide.com/
  $default_width: cx
  $default_height: cy

  # Switch padding, i.e. distance from center of switch (Point) to 
  # the nearest edge of the PCB. Essentially a 1mm pad. Useful
  # for adjustment operations in relation to a Point.
  cpx: 1 + kx / 2
  cpy: 1 + ky / 2

  # Controller dimensions
  nice_nano_length: 33
  nice_nano_width: 18.3

  # Distance between highest finger and top of board
  middle_finger_prominence: 3.5

  mounting_hole_radius: 1.8
points:
  zones:
    matrix:
      anchor:
        # Cancel out rotations from column splay
        rotate: 6
        # Adjust translation for KiCad
        shift: [100, -100]
      key:
        padding: ky
        spread: kx
      columns:
        pinky:
          rows:
            bottom:
                column_net: P18
            home:
                column_net: P15
            top:
                column_net: P14
        ring:
          key:
            splay: -3
            spread: kx + 0.5
            stagger: ky - 2
          rows:
            bottom:
                column_net: P16
            home:
                column_net: P10
            top:
                column_net: P9
        middle:
          key:
            splay: -3
            spread: kx + 0.5
            stagger: 3
          rows:
            bottom:
                column_net: P8
            home:
                column_net: P7
            top:
                column_net: P6
        pointer:
          key:
            stagger: -6
          rows:
            bottom:
                column_net: P5
            home:
                column_net: P4
            top:
                column_net: P3
        inner:
          key:
            stagger: -2
          rows:
            bottom:
                column_net: P2
            home:
                column_net: P0
            top:
                column_net: P1
      rows:
        bottom:
        home:
        top:
    thumbs:
      anchor:
        ref: matrix_pointer_bottom
        shift: [4, -22]
      key:
        padding: 1ky
        spread: 1kx
      columns:
        tucky:
          key:
            column_net: P19
        middle:
          key:
            shift: [2.4, -1.8]
            splay: -13
            column_net: P20
        reachy:
          key:
            shift: [5.1, -3.2]
            splay: -13
            column_net: P21
      rows:
        cluster:
outlines:  
  _keycaps:
    - what: rectangle
      where: true
      size: [kx, ky]
  _switch_holes:
    - what: rectangle
      where: true
      size: [14, 14]
  _matrix:
    - what: rectangle
      where: /^matrix_/
      size: [kx, ky]
    - what: polygon
      points:
        - ref: matrix_ring_top
          shift: [0cpx, 0.5ky]
        - shift: [2cpx, 0]
        - ref: matrix_middle_bottom
          shift: [0, -0.5ky]
        - shift: [-2cpx, 0]
    - what: polygon
      points:
        - ref: matrix_pinky_top
          shift: [0, 0.5ky]
        - shift: [1kx, 0]
        - ref: matrix_ring_bottom
          shift: [0, -0.5ky]
        - shift: [-1kx, 0]
  _thumbs:
    - what: rectangle
      where: /thumbs_/
      size: [kx, ky]
    - what: polygon
      points:
        - ref: thumbs_tucky_cluster
          shift: [0.5kx, 0.5ky]
        - ref: thumbs_middle_cluster
          shift: [-0.5kx, 0.5ky]
        - ref: thumbs_middle_cluster
          shift: [0.5kx, 0.5ky]
        - ref: thumbs_reachy_cluster
          shift: [-0.5kx, 0.5ky]
        - ref: thumbs_reachy_cluster
        - ref: thumbs_reachy_cluster
          shift: [-0.5kx, -0.5ky]
        - ref: thumbs_tucky_cluster
          shift: [0.5kx, -0.5ky]
        - ref: thumbs_tucky_cluster
  # Connect the thumbs to the matrix
  _matrix_thumb_connector:
    - what: polygon
      points:
        - ref: thumbs_tucky_cluster
          shift: [-0.5kx - 0, 2cpy]
        - ref: matrix_inner_bottom
          shift: [1cpx, 1cpy]
        - ref: matrix_inner_bottom
          shift: [1cpx, -3cpy]
        - ref: thumbs_tucky_cluster
          shift: [-0.5kx - 0, 0]
  _controller:
    - what: polygon
      fillet: 1
      adjust: &controller
        ref: matrix_inner_bottom
        # Let's define the center for this outline so
        # we can reuse it in the PCB
        shift: [1kx / 2 + 4 + nice_nano_width / 2, 5 + -1cy / 2 + nice_nano_length / 2]
      points:
        # start at top left
        - shift: [-nice_nano_width / 2, -nice_nano_length / 2]
        - shift: [0, nice_nano_length]
        - shift: [nice_nano_width, 0]
        - shift: [0, -nice_nano_length]
  _controller_area:
    - what: polygon
      fillet: 1
      adjust: *controller
      points:
        # start at top right of controller
        - shift: [nice_nano_width / 2, nice_nano_length / 2]
        - shift: [0, -nice_nano_length - 1ky - 5]
        - shift: [-nice_nano_width - kx, 0]
        - shift: [0, nice_nano_length + 1ky + 5]
  _battery:
    # 20 x 30, the one totem uses
    - what: polygon
      adjust: &battery_outline
        ref: thumbs_tucky_cluster
        shift: [-1cpx - 30 - 4, -0.5ky]
      points:
        - shift: [0, 0]
        - shift: [30, 0]
        - shift: [0, 20]
        - shift: [-30, 0]
  _jst:
    # 8 x 4.5 is the actual component, but may need to adjust
    # to match the footprint. Trying my best!
    - what: polygon
      adjust: &jst_connector
        ref: thumbs_tucky_cluster
        shift: [-1cpx - 47, -0.5ky + 4]
      points:
        # Manually shift the start point to more closely match the PCB
        - shift: [-2, -4]
        - shift: [8, 0]
        - shift: [0, 4.5]
        - shift: [-8, 0]
  # Fills out bottom corner from pink to thumb cluster.
  # Makes a space for the JST connector
  _bottom_left:
    - what: polygon
      fillet: 1
      points:
        - ref: matrix_pinky_home
          shift: [-0.5kx, 0]
        - shift: [70, 0]
        - ref: thumbs_tucky_cluster
          shift: [0cpx, -0.5ky]
        # Just eyeballing an intersection
        - shift: [-65, 0]
        - ref: matrix_pinky_bottom
          shift: [-0.5kx, -0.5ky - 5]
  _debug_rectangle:
    - what: polygon
      points:
        - shift: [-80, 130]
        - shift: [250, 0]
        - shift: [0, -230]
        - shift: [-250, 0]
  _power_switch:
    # 6.7x2.6mm body and a little 1.3x1.5 actuator
    # body
    - what: polygon
      adjust: &power_switch
        ref: matrix_middle_top
        # Coordinates are all based on the center, so adjust manually
        # based on 6.7x2.6 size
        shift: [-37 + 6.7/2, 1cpy - middle_finger_prominence - 2.6/2 - 0.2]
      points:
        - shift: [-6.7, 2.6/2]
        - shift: [6.7, 0]
        - shift: [0, -2.6]
        - shift: [-6.7, 0]
    # actuator
    - what: polygon
      adjust: *power_switch
      points:
        - shift: [-6.7 + 1.6, 2.6]
        - shift: [1.3, 0]
        - shift: [0, -1.5]
        - shift: [-1.3, 0]
  _reset_switch:
    # 4.7x3.5 body and 2.6x1 button
    # body
    - what: polygon
      adjust: &reset_switch
        # Coordinates are all based on the center, so adjust manually
        # based on 4.7x3.5 body size (also 2.6x1 buttton)
        ref: matrix_middle_top
        shift: [33 + 4.7/2, 1cpy - middle_finger_prominence - 3.5/2]
      points:
        - shift: [-4.7/2, 3.5/2]
        - shift: [4.7, 0]
        - shift: [0, -3.5]
        - shift: [-4.7, 0]
    # button
    - what: polygon
      adjust: *reset_switch
      points:
        - shift: [-4.7/2 + 1, 3.5/2 + 1]
        - shift: [2.6, 0]
        - shift: [0, -1]
        - shift: [-2.6, 0]
  # Fills out top area (mostly left) for power switch
  _top_left:
    - what: polygon
      fillet: 1
      adjust:
        ref: matrix_middle_top
        shift: [0, 1cpy - middle_finger_prominence]
      points:
        - shift: [-45, 0]
        - shift: [94, 0]
        - shift: [0, -30]
        - shift: [-94, 0]
  _mounting_holes:
    - what: circle
      adjust: &top_left_hole
        ref: matrix_pinky_top
        shift: [0, 21]
      radius: mounting_hole_radius
    - what: circle
      adjust: &top_right_hole
        ref: matrix_inner_top
        shift: [1cpx, 1cpy + 1]
      radius: mounting_hole_radius
    - what: circle
      adjust: &bottom_middle_hole
        ref: matrix_middle_bottom
        shift: [0cpx, -1cpy - 3]
      radius: mounting_hole_radius
    - what: circle
      adjust: &bottom_right_hole
        ref: thumbs_reachy_cluster
        shift: [0cpx - 4, 1cpy + 5]
      radius: mounting_hole_radius
    - what: circle
      adjust: &bottom_left_hole
        ref: matrix_pinky_bottom
        shift: [-0.5kx + 3, -0.5ky - 3.5]
      radius: mounting_hole_radius
  left_board:
    - name: _matrix
    - name: _thumbs
    - name: _matrix_thumb_connector
    - name: _controller_area
    - name: _controller
    - name: _bottom_left
    - name: _top_left
    #- name: _debug_rectangle
  switch_plate:
    - name: left_board
    - operation: subtract
      name: _switch_holes
  preview:
    - name: left_board
    - name: _keycaps
      operation: subtract
    - name: _battery
      operation: subtract
    - name: _jst
      operation: subtract
    - name: _controller
      operation: subtract
    - name: _mounting_holes
      operation: stack
    - name: _power_switch
      operation: stack
    - name: _reset_switch
      operation: stack
pcbs:
  left:
    # Required, since footprints are KiCad 8 only
    template: kicad8
    outlines:
      main:
        outline: left_board
      battery_guide:
        outline: _battery
        layer: F.SilkS
    footprints:
      choc_hotswap:
        what: ceoloide/switch_choc_v1_v2
        where: true
        params:
          choc_v2_support: false
          include_corner_marks: true
          include_keycap: true
          keycap_height: ky
          keycap_width: kx
          # hotswap_3dmodel_filename: 3dmodels/ScottoKeebs_Hotswap.3dshapes/Choc_V1.step
          # keycap_3dmodel_filename: 3dmodels/ScottoKeebs_CAD.3dshapes/Choc_1.00u_CAD.step
          # switch_3dmodel_filename: 3dmodels/ScottoKeebs_Choc.3dshapes/Choc_V1.step
          from: "{{column_net}}"
          to: "GND"
      nice_nano:
        what: ceoloide/mcu_nice_nano
        params:
          # mcu_3dmodel_filename: 3dmodels/ScottoKeebs_MCU.3dshapes/Nice_Nano_V2.step
          # mcu_3dmodel_xyz_offset: [0, 0, 3]
        where: *controller
      power_switch:
        what: ceoloide/power_switch_smd_side
        # top left
        where:
          <<: *power_switch
          # Spin so it's facing up
          rotate: 90
        params:
          from: Braw
          to: RAW
      reset_switch:
        what: ceoloide/reset_switch_smd_side
        # top right, near the USB port
        where: *reset_switch 
        params:
          from: GND
          to: RST
      battery_connector:
        what: ceoloide/battery_connector_jst_ph_2
        where:
          <<: *jst_connector
          # Spin so the plug faces towards the thumbs
          rotate: 90
        params:
          BAT_P: Braw
          BAT_N: GND
      battery_text:
        what: ceoloide/utility_text
        where:
          # Slide it left, just under the pinky
          ref: thumbs_tucky_cluster
          shift: [-35, -1cpy + 5]
        params:
          text: "Battery"
      top_left_hole:
        what: ceoloide/mounting_hole_plated
        where: *top_left_hole
      top_right_hole:
        what: ceoloide/mounting_hole_plated
        where: *top_right_hole
      bottom_left_hole:
        what: ceoloide/mounting_hole_plated
        where: *bottom_left_hole
      bottom_middle_hole:
        what: ceoloide/mounting_hole_plated
        where: *bottom_middle_hole
      bottom_right_hole:
        what: ceoloide/mounting_hole_plated
        where: *bottom_right_hole
# TODO: Try that intersection function again, but orient the point first
# TODO: figure out reversible settings
# TODO: Try out flatfootfox's cutouts for underside of board
# TODO: Bottom PCB with cutouts for case bottom!
# TODO: Minimal case
# TODO: Try out infused-kim's ergogen/kicad helpers to preserve routing
# TODO: Illustrations!
# TODO: TOP PCB as switch plate? Sandwich in between with foam or something?
# TODO: Light guides for LEDs
# TODO: Little reset pusher tab (I think Forager does this)
# TODO: Peel-away super duper low profile controller sockets like Tern
