meta:
  engine: 4.1.0 # Min Ergogen version for KiCad 8 footprints
units:
  # Proxy spacing variables, choc spacing
  kx: cx
  ky: cy

  # For the preview at https://ergogen.ceoloide.com/
  $default_width: cx
  $default_height: cy

  # keywell padding
  kpx: kx + 0.5
  kpy: ky + 0.5

  # Board padding, i.e. distance from center of keycap (Point) to 
  # the nearest edge of the PCB. Essentially a 1mm pad.
  cpx: 1 + kx / 2
  cpy: 1 + ky / 2

  # controller dimensions
  nice_nano_length: 34.1
  nice_nano_width: 18.3
points:
  zones:
    matrix:
      key:
        padding: ky
        spread: kx
      columns:
        pinky:
        ring:
          key:
            splay: -3
            spread: kx + 0.5
            stagger: ky - 2
        middle:
          key:
            splay: -3
            spread: kx + 0.5
            stagger: 3
        pointer:
          key:
            stagger: -6
        inner:
          key:
            stagger: -2
      rows:
        bottom:
        middle:
        top:
    thumbs:
      anchor:
        ref: matrix_pointer_bottom
        shift: [6, -22]
      key:
        padding: 1ky
        spread: 1kx
      columns:
        tucky:
        middle:
          key:
            shift: [2, -1.5]
            splay: -10
        reachy:
          key:
            shift: [4.25, -2.5]
            splay: -10
      rows:
        cluster:
  mirror:
    ref: thumbs_reachy_cluster
    distance: 2kx
outlines:
  # Shows the keycaps
  keycaps:
    - what: rectangle
      where: true
      size: [kx, ky]
  switch_holes:
    - what: rectangle
      where: true
      size: [14, 14]
  matrix:
    - what: rectangle
      where: /^matrix_/
      size: [kx, ky]
      expand: 1
  thumbs:
    - what: rectangle
      where: /^thumbs_/
      size: [kx, ky]
      expand: 1
  # Connect the thumbs to the matrix
  matrix_thumb_connector:
    - what: polygon
      points:
        - ref: thumbs_tucky_cluster
          shift: [-1cpx - 0, 2cpy]
        - ref: matrix_inner_bottom
          shift: [1cpx, 1cpy]
        - ref: matrix_inner_bottom
          shift: [1cpx, -3cpy]
        - ref: thumbs_tucky_cluster
          shift: [-1cpx - 0, 0]
  # Fix the splay gap between thumbs.
  thumb_bandaid:
    - what: polygon
      points:
        - ref: thumbs_middle_cluster
          shift: [1cpx, 1cpy]
        - ref: thumbs_reachy_cluster
          shift: [-1cpx, 1cpy]
        - ref: thumbs_middle_cluster
          shift: [1cpx, -1cpy]
        - ref: thumbs_reachy_cluster
          shift: [-1cpx, -1cpy]
  # Fix the splay gap between ring and middle fingers
  matrix_bandaid:
    - what: polygon
      points:
        - ref: matrix_ring_top
          shift: [0cpx, 1cpy]
        - ref: matrix_ring_top
          shift: [2cpx, 1cpy]
        - ref: matrix_ring_top
          shift: [2cpx, -1cpy]
        - ref: matrix_ring_top
          shift: [1cpx, -1cpy]
  controller:
    - what: polygon
      adjust: 
        ref: matrix_inner_bottom
        shift: [1cpx + 3, -1cpx + 1]
      points:
        - shift: [0, 0]
        - shift: [0, nice_nano_length]
        - shift: [nice_nano_width, 0]
        - shift: [0, -nice_nano_length]
  controller_area:
    - what: polygon
      adjust:
        ref: matrix_inner_bottom
        shift: [0, -2cpy]
      points:
        - shift: [0, 0]
        - shift: [0, 1cpy + 1]
        - shift: [0, nice_nano_length]
        - shift: [1cpx + 3, 0]
        - shift: [nice_nano_width + 3, 0]
        - shift: [0, -nice_nano_length]
        - shift: [0, -2cpy - 2]
  board2:
    - name: matrix
    - name: thumbs
    - name: matrix_thumb_connector
    - name: thumb_bandaid
    - name: matrix_bandaid
    - name: controller_area
    - name: controller
      operation: stack
  switch_plate:
    - name: board2
    - operation: subtract
      name: switch_holes
pcbs:
  left:
    template: kicad8 # Required, since footprints are KiCad 8 only
    outlines:
      main:
        outline: board2
    footprints:
      choc_hotswap:
        what: ceoloide/switch_choc_v1_v2
        where: true
        params:
          choc_v2_support: false
          keycap_height: ky
          keycap_width: kx
          hotswap_3dmodel_filename: 3dmodels/ScottoKeebs_Hotswap.3dshapes/Choc_V1.step
          switch_3dmodel_filename: 3dmodels/ScottoKeebs_Choc.3dshapes/Choc_V1.step
          # TODO: These are certainly broken
          from: "{{name}}_from"
          to: "{{name}}_to"
      nice_nano:
        what: ceoloide/mcu_nice_nano
        params:
          mcu_3dmodel_filename: 3dmodels/ScottoKeebs_MCU.3dshapes/Nice_Nano_V2.step
          mcu_3dmodel_xyz_offset: [0, 0, 3]
        where:
          # Align the bottom of the nice nano with the bottom keycap
          ref: matrix_inner_bottom
          shift: [1kx + 3, nice_nano_length / 2 - kx / 2]
          rotate: 0
      # TODO: reset button
      # TODO: power switch
      # TODO: JST plug
      # TODO: battery outline
      # TODO: speaker?
      # TODO: haptic?
      # TODO: LED?
