units:
  # Proxy spacing variables, choc spacing
  kx: cx
  ky: cy
  # For the preview at https://ergogen.ceoloide.com/
  $default_width: cx
  $default_height: cy
  # keywell padding
  kpx: kx + 0.5
  kpy: ky + 0.5
  # Board padding, i.e. space between keycap and edge of board
  cpx: 2 + kx / 2
  cpy: 2 + ky / 2
points:
  zones:
    matrix:
      key:
        padding: ky
        spread: kx
      columns:
        pinky:
          key:
            # TODO: find a better way to do this. The other columns
            # should add up to cancel out this splay so that the 
            # inner columns are straight up and down.
            splay: 13
        ring:
          key:
            spread: kx + 2
            splay: -5
            stagger: ky
        middle:
          key:
            spread: kx + 2
            splay: -5
            stagger: 3
        pointer:
          key:
            spread: kx + 1
            splay: -3
            stagger: -6
        inner:
          key:
            stagger: -2
      rows:
        bottom:
        middle:
        top:
    thumbs:
      anchor:
        ref: matrix_pointer_bottom
        shift: [0, -24]
      key:
        padding: 1ky
        spread: 1kx
      columns:
        tucky:
        middle:
          key:
            shift: [2, -1.5]
            splay: -10
        reachy:
          key:
            shift: [4.25, -2.5]
            splay: -10
      rows:
        cluster:
outlines:
  # Shows the keycaps
  keycaps:
    - what: rectangle
      where: true
      size: [kx, ky]
  # Shows keycaps with a tiny bit of spacing around them
  keywells:
    - what: rectangle
      where: true
      size: [kpx, kpy]
  # Just the outline of the PCB
  board:
    - what: polygon
      fillet: 2
      points:
        - ref: matrix_pinky_top
          shift: [-1cpx, 1cpy]
        - ref: matrix_ring_top
          shift: [-1cpx, 1cpy]
        - ref: matrix_middle_top
          shift: [-1cpx, 1cpy]
        - ref: matrix_middle_top
          shift: [1cpx, 1cpy]
        - ref: matrix_inner_top
          shift: [1cpy, 1cpy]
        - ref: thumbs_reachy_cluster
          shift: [1cpx, 1cpy]
        - ref: thumbs_reachy_cluster
          shift: [1cpx, -1cpy]
        - ref: thumbs_middle_cluster
          shift: [1cpx, -cpy]
        - ref: thumbs_middle_cluster
          shift: [-1cpx, -cpy]
        - ref: thumbs_tucky_cluster
          shift: [-1cpx, -1cpy]
        - ref: matrix_pinky_bottom
          shift: [-1cpx, -1cpy]
  # Just for visualization purposes.
  # Shows the outline of the PCB overlayed with keycaps
  combo:
    - name: board
    - operation: subtract
      name: keycaps