meta:
  # Min Ergogen version for KiCad 8 footprints
  engine: 4.1.0
units:
  # Proxy spacing variables, choc spacing
  kx: cx
  ky: cy

  # For the preview at https://ergogen.ceoloide.com/
  $default_width: cx
  $default_height: cy

  # Switch padding, i.e. distance from center of switch (Point) to 
  # the nearest edge of the PCB. Essentially a 1mm pad. Useful
  # for adjustment operations in relation to a Point.
  cpx: 1 + kx / 2
  cpy: 1 + ky / 2

  # Controller dimensions
  nice_nano_length: 33
  nice_nano_width: 17.9
  xiao_length: 21
  xiao_width: 17.5

  # XX2030 battery
  battery_sm_width: 30
  battery_sm_length: 20

  # joycon battery
  battery_lg_width: 51
  battery_lg_length: 24.1

  # includes full courtyard size
  jst_connector_width: 12.35
  jst_connector_length: 6.9

  # The footprint's "origin" is not right in the center,
  # it's just a little ways from the left edge
  jst_connector_offset: -jst_connector_width / 2 + 1.85

  power_switch_width: 6.7
  power_switch_length: 2.6

  reset_switch_width: 4.7
  reset_switch_length: 3.5

  # Distance between highest finger and top of board
  middle_finger_prominence: 3

  mounting_hole_radius: 1.1

  total_matrix_splay: 6

  inner_to_mcu_distance: 4

  fan_outer_radius: 5kx
points:
  zones:
    matrix:
      anchor:
        # Cancel out rotations from column splay
        rotate: total_matrix_splay
        # Adjust translation for KiCad
        shift: [100, -100]
      key:
        padding: ky
        spread: kx
        tags: [key]
      columns:
        pinky:
          rows:
            bottom:
                column_net: P18
            home:
                column_net: P15
            top:
                column_net: P14
        ring:
          key:
            splay: -total_matrix_splay / 2
            spread: kx + 0.5
            stagger: ky - 2
          rows:
            bottom:
                column_net: P16
            home:
                column_net: P10
            top:
                column_net: P9
        middle:
          key:
            splay: -total_matrix_splay / 2
            spread: kx + 0.5
            stagger: 3
          rows:
            bottom:
                column_net: P8
            home:
                column_net: P7
            top:
                column_net: P6
        pointer:
          key:
            stagger: -6
          rows:
            bottom:
                column_net: P5
            home:
                column_net: P4
            top:
                column_net: P3
        inner:
          key:
            stagger: -2
          rows:
            bottom:
                column_net: P2
            home:
                column_net: P0
            top:
                column_net: P1
      rows:
        bottom:
        home:
        top:
    thumbs:
      anchor:
        ref: matrix_pointer_bottom
        shift: [4, -22]
      key:
        padding: 1ky
        spread: 1kx
        tags: [key]
      columns:
        tucky:
          key:
            column_net: P19
        middle:
          key:
            shift: [2.4, -1.8]
            splay: -13
            column_net: P20
        reachy:
          key:
            shift: [5.1, -3.2]
            splay: -13
            column_net: P21
      rows:
        cluster:
    case_tl:
      key.tags: [case, tl]
      anchor:
        aggregate:
          method: intersect
          parts:
            - ref: matrix_middle_top
              shift: [0, 1cpy - middle_finger_prominence]
              rotate: -90
            - ref: matrix_pinky_top
              shift: [-1cpx, 0]
              rotate: -2total_matrix_splay
    case_tr:
      key.tags: [case, tr]
      anchor:
        aggregate:
          method: intersect
          parts:
            - ref: case_tl
              rotate: 90
            - ref: matrix_inner_top
              shift: [1cpx, -1cpy]
    case_bl:
      key.tags: [case, bl]
      anchor:
        aggregate:
          method: intersect
          parts: 
            - ref: matrix_pinky_bottom
              shift: [-1cpx, -1cpy]
            - ref: thumbs_tucky_cluster
              shift: [0, -1cpy]
              rotate: -90
    mcu_nano:
      key.tags: [mcu, nice_nano]
      anchor:
        ref: matrix_inner_top
        shift: [1kx / 2 + inner_to_mcu_distance + nice_nano_width / 2, 5 + -1cy / 2 - nice_nano_length / 2]
    mcu_xiao:
      key.tags: [mcu, xiao]
      anchor:
        ref: matrix_ring_top
        rotate: -3 - 90
        shift: [-1.2kx, 0.2kx]
    power_switch:
      key.tags: [power_switch]
      anchor:
        ref: case_tl
        shift: [9, -power_switch_length / 2 - 0.5]
    reset_switch:
      key.tags: [reset_switch]
      anchor:
        ref: case_tr
        shift: [-9, -reset_switch_length / 2]
    jst_connector:
      key.tags: [jst_connector]
      anchor:
        ref: case_bl
        rotate: 90
        shift: [8, jst_connector_length / 2]
    battery_sm:
      key.tags: [battery, battery_sm]
      anchor:
        ref: thumbs_tucky_cluster
        shift: [-1cpx - battery_sm_width / 2 - 3.5, -1cpy + battery_sm_length / 2]
    battery_lg:
      anchor: battery_sm
    screw_tl:
      key.tags: [screw, tl]
      anchor:
        ref: case_tl
        shift: [3, -6]
    screw_tr:
      key.tags: [screw, tr]
      anchor:
        ref: case_tr
        shift: [-3, -2.5]
    screw_bl:
      key.tags: [screw, bl]
      anchor:
        ref: case_bl
        shift: [3, 3]
    screw_bm:
      key.tags: [screw, bm]
      anchor:
        - ref: matrix_middle_bottom
          shift: [0, -1cpy - 3]
    screw_br:
      key.tags: [screw, br]
      anchor:
        ref: thumbs_reachy_cluster
        shift: [-3, 1cpy + 5]
    thumb_edge_bl:
      anchor:
        ref: thumbs_tucky_cluster
        shift: [-1cpx, -1cpy]
    thumb_edge_tl:
      anchor:
        aggregate:
          method: intersect
          parts:
            - thumb_edge_bl
            - ref: matrix_pointer_bottom
              shift: [-1cpx, -0.5cy]
              rotate: 90
outlines:  
  _keycaps:
    - what: rectangle
      where: [key]
      size: [kx, ky]
  _switch_holes:
    - what: rectangle
      where: [key]
      size: [14, 14]
  _matrix:
    - what: rectangle
      where: /matrix/
      size: [2cpx, 2cpy]
    # patch gaps between columns
    - what: polygon
      points:
        - ref: matrix_ring_top
          shift: [0cpx, 1cpy]
        - shift: [2cpx, 0]
        - ref: matrix_middle_bottom
          shift: [0, -cpy]
        - shift: [-2cpx, 0]
    - what: polygon
      points:
        - ref: matrix_pinky_top
          shift: [0, 1cpy]
        - shift: [1kx, 0]
        - ref: matrix_ring_bottom
          shift: [0, -1cpy]
        - shift: [-1kx, 0]
  _thumbs:
    - what: rectangle
      where: /thumbs_/
      size: [2cpx, 2cpy]

    - what: polygon
      points:
        - ref: thumbs_tucky_cluster
          shift: [1cpx, 1cpy]
        - ref: thumbs_middle_cluster
          shift: [-1cpx, 1cpy]
        - ref: thumbs_middle_cluster
          shift: [1cpx, 1cpy]
        - ref: thumbs_reachy_cluster
          shift: [-1cpx, 1cpy]
        - ref: thumbs_reachy_cluster
          shift: [0, 1cpy]
        - ref: thumbs_reachy_cluster
        - ref: thumbs_reachy_cluster
          shift: [-1cpx, -1cpy]
        - ref: thumbs_tucky_cluster
          shift: [1cpx, -1cpy]
        - ref: thumbs_tucky_cluster
  # Connect the thumbs to the matrix
  _matrix_thumb_connector:
    - what: polygon
      points:
        - ref: thumbs_tucky_cluster
          shift: [-1cpx, 2cpy]
        - ref: matrix_inner_bottom
          shift: [1cpx, 1cpy]
        - ref: matrix_inner_bottom
          shift: [1cpx, -3cpy]
        - ref: thumbs_tucky_cluster
          shift: [-1cpx, 0]
  # Matches the actual nice nano shape, just for previewing
  _controller:
    - what: rectangle
      where: [nice_nano]
      size: [nice_nano_width, nice_nano_length]
  _tmp_xiao:
    - what: rectangle
      where: [xiao]
      size: [xiao_width, xiao_length]
  # Extend the outline to ensure we leave space for the controller
  _controller_area:
    - what: polygon
      points:
        - ref: mcu_nano
          shift: [nice_nano_width / 2 + 1, nice_nano_length / 2 + 1]
        - aggregate:
            method: intersect
            parts:
              - ref: mcu_nano
                shift: [nice_nano_width / 2 + 1, nice_nano_length / 2 + 1]
              - ref: thumbs_reachy_cluster
                shift: [-kx, 1cpy]
                rotate: 90
        - aggregate:
            method: intersect
            parts:
              - ref: mcu_nano
                shift: [-nice_nano_width / 2 - inner_to_mcu_distance, nice_nano_length / 2 + 1]
              - ref: thumbs_middle_cluster
                shift: [-kx, 1cpy]
                rotate: 90
        - ref: mcu_nano
          shift: [-nice_nano_width / 2 - inner_to_mcu_distance, nice_nano_length / 2 + 1]
  # so we know where to build the case over the controller
  _controller_cover:
    - what: outline
      name: _controller_area
    # Cut out around the thumb fan
    - what: circle
      radius: fan_outer_radius
      operation: subtract
      where:
        ref: thumbs_middle_cluster
        shift: [0, 1cpy - fan_outer_radius + 2]
  _battery_hole:
    # 20 x 30, the one totem uses
    - what: rectangle
      where: [battery_sm]
      size: [battery_sm_width, battery_sm_length]
      expand: 1
  # Useful to build a part that doesn't have a hole for the battery
  _battery_filler:
    - what: rectangle
      where: battery_sm
      size: [battery_sm_width, battery_sm_length]
  _jst_connector:
    - what: rectangle
      where: jst_connector
      size: [jst_connector_length, jst_connector_width]
      # The JST connector's footprint is not centered. Make up for that here
      # so our visual lines up with the final product
      adjust.shift: [0, jst_connector_offset]
  _jst_hole:
    - what: outline
      name: _jst_connector
      expand: 0.5
  # Fills out bottom corner from pink to thumb cluster.
  # Makes a space for the JST connector
  _bottom_left:
    - what: polygon
      points:
        - ref: matrix_pinky_top
          shift: [-1cpx, 1cpy]
        - shift: [70, 0]
        - ref: thumbs_tucky_cluster
          shift: [0cpx, -1cpy]
        - case_bl
  _power_switch:
    - what: rectangle
      where: power_switch
      size: [power_switch_width, power_switch_length]
    # actuator
    - what: rectangle
      where: power_switch
      size: [1.3, 1.5]
      adjust:
        shift: [0, power_switch_length / 2 + 1.5 / 2]
  _power_switch_hole:
    - what: outline
      name: _power_switch
      expand: 1
      adjust:
        shift: [0, 0.5]
  _reset_switch:
    # body
    - what: rectangle
      where: reset_switch
      size: [reset_switch_width, reset_switch_length]
    # button
    - what: rectangle
      where: reset_switch
      size: [2.6, 1]
      adjust:
        shift: [0, reset_switch_length / 2 + 0.5]
  _reset_switch_hole:
    - what: outline
      name: _reset_switch
      expand: 1
      adjust:
        shift: [0, 0.5]
  # Fills out top area (mostly left) for power switch
  _top_left:
    - what: polygon
      points:
        - ref: case_tl
        - ref: case_tr
        - shift: [0, -65]
        - ref: matrix_pinky_bottom
          shift: [-1cpx, 0]
  _mounting_holes:
    - what: circle
      where: screw_tl
      radius: mounting_hole_radius
    - what: circle
      where: screw_tr
      radius: mounting_hole_radius
    - what: circle
      where: screw_bm
      radius: mounting_hole_radius
    - what: circle
      where: screw_br
      radius: mounting_hole_radius
    - what: circle
      where: screw_bl
      radius: mounting_hole_radius
  _thumb_fan_left_edge:
    - what: polygon
      operation: stack
      points:
        - thumb_edge_bl
        - thumb_edge_tl
  _base:
    - name: _matrix
    - name: _thumbs
    - name: _matrix_thumb_connector
    - name: _controller_area
    - name: _bottom_left
    - name: _top_left
    - name: _battery_filler
  base:
    - what: outline
      name: _base
      fillet: 1
    - name: _mounting_holes
      operation: subtract
  _left_board:
    - name: _matrix
    - name: _thumbs
    - name: _matrix_thumb_connector
    - name: _bottom_left
    - name: _top_left
    - name: _controller_area
    - name: _battery_hole
      operation: subtract
  left_board:
    - what: outline
      name: _left_board
      fillet: 1
    - name: _mounting_holes
      operation: subtract
  _keywell:
    - name: _matrix
    - name: _thumbs
    - name: _matrix_thumb_connector
  keywell:
    - what: outline
      name: _keywell
      fillet: 0.5
  _switch_plate:
    - name: _matrix
    - name: _thumbs
    - name: _matrix_thumb_connector
    - name: _bottom_left
    - name: _top_left
    - name: _battery_hole
      operation: subtract
    - name: _power_switch_hole
      operation: subtract
    - name: _reset_switch_hole
      operation: subtract
    - name: _jst_hole
      operation: subtract
    - name: _switch_holes
      operation: subtract
  switch_plate:
    - what: outline
      name: _switch_plate
      fillet: 1
    - name: _mounting_holes
      operation: subtract  
  _ground_plane:
    - what: polygon
      points:
        - ref: matrix_pinky_top
          shift: [-1cpx, 0]
        - ref: matrix_ring_top
          shift: [-1cpx, 0]
        - ref: matrix_middle_top
          shift: [-1cpx, 0]
        - ref: matrix_middle_top
          shift: [1cpx, 0]
        - ref: matrix_pointer_top
          shift: [1cpx, 0]
        - ref: matrix_inner_top
          shift: [1cpx, 0]
        - ref: matrix_inner_bottom
          shift: [1cpx, 0]
        - ref: thumbs_reachy_cluster
          shift: [1cpx, 0]
        - ref: thumbs_middle_cluster
          shift: [0cpx, 0]
        - ref: thumbs_tucky_cluster
          shift: [-1cpx, 0]
        - ref: matrix_pinky_bottom
          shift: [-1cpx, 0]
  preview:
    - name: left_board
    - name: _keycaps
      operation: subtract
    - name: _jst_connector
      operation: stack
    - name: _battery_hole
      operation: stack
    - name: _mounting_holes
      operation: stack
    - name: _power_switch
      operation: stack
    - name: _reset_switch
      operation: stack
    - name: _controller_cover
      operation: stack
    - name: _controller
      operation: stack
    - name: _thumb_fan_left_edge
      operation: stack
pcbs:
  left:
    # Required, since footprints are KiCad 8 only
    template: kicad8
    outlines:
      main:
        outline: left_board
    footprints:
      choc_hotswap:
        what: ceoloide/switch_choc_v1_v2
        where: [key]
        params:
          choc_v2_support: false
          include_corner_marks: true
          include_keycap: true
          include_centerhole_net: true
          keycap_height: ky
          keycap_width: kx
          reversible: true

          hotswap_3dmodel_filename: ${EG_INFUSED_KIM_3D_MODELS}/Choc_V1_Hotswap.step
          hotswap_3dmodel_xyz_offset: [0, 0, -1.6]
          hotswap_3dmodel_xyz_rotation: [0, 180, 180]

          keycap_3dmodel_filename: ${EG_INFUSED_KIM_3D_MODELS}/Choc_V1_Keycap_MBK_White_1u.step
          keycap_3dmodel_xyz_offset: [0, 0, -8]
          keycap_3dmodel_xyz_rotation: [0, 180, 0]

          switch_3dmodel_filename: ${EG_INFUSED_KIM_3D_MODELS}/Choc_V1_Switch.step
          switch_3dmodel_xyz_offset: [0, 0, -1.5]
          switch_3dmodel_xyz_rotation: [0, 180, 180]

          from: "{{column_net}}"
          to: "GND"
      nice_nano:
        what: ceoloide/mcu_nice_nano
        params:
          reversible: true
          mcu_3dmodel_filename: ${EG_INFUSED_KIM_3D_MODELS}/Nice_Nano_V2.step
          # Z up 1mm for MCU thickness and an additional 1.14 for https://www.advanced.com/products/peel-a-way-removable-carriers/peel-a-way-strips/2-54mm-pitch
          mcu_3dmodel_xyz_offset: [0, 0, 2.14]
          mcu_3dmodel_xyz_rotation: [0, 180, 0]
        where: mcu_nano
      power_switch:
        what: ceoloide/power_switch_smd_side
        # top left
        where: power_switch
        adjust:
          # Spin so it's facing up
          rotate: 90
        params:
          reversible: true
          from: Braw
          to: RAW
          switch_3dmodel_filename: ${EG_INFUSED_KIM_3D_MODELS}/Switch_Power.step
          switch_3dmodel_xyz_rotation: [-90, 0, -90]
      reset_switch:
        what: ceoloide/reset_switch_smd_side
        # top right, near the USB port
        where: reset_switch
        params:
          reversible: true
          # switch_3dmodel_filename: ${EG_INFUSED_KIM_3D_MODELS}/Switch_Reset.step
          # switch_3dmodel_xyz_offset: [0, 0, 0]
          # switch_3dmodel_xyz_rotation: [-90, 0, 180]
          from: GND
          to: RST
      jst_connector:
        what: ceoloide/battery_connector_jst_ph_2
        where: jst_connector
        params:
          reversible: true
          # battery_3dmodel_filename: ${DIMETRODON_KICAD}/3dmodels/JST-S2B-PH-K-S.STEP
          # battery_3dmodel_xyz_offset: [1, 0, 0]
          # battery_3dmodel_xyz_rotation: [180, 0, 180]
          BAT_P: Braw
          BAT_N: GND
      battery_text:
        what: ceoloide/utility_text
        where:
          ref: thumbs_tucky_cluster
          shift: [-1cpx - 30 + 1, -1cpy + 22]
        params:
          reversible: true
          text: "602030 Battery"
      jlcpcb_order_number_text:
        what: ceoloide/utility_text
        where: mcu_nano
        params:
          text: JLCJLCJLCJLCJLCJLCJLC
          reversible: true
        adjust:
          shift: [0, -nice_nano_length / 2 - 1]
      ergogen_logo:
        what: ceoloide/utility_ergogen_logo
        where: mcu_nano
        params:
          reversible: true
        adjust:
          shift: [0, -nice_nano_length / 2 - 7]  
      top_left_hole:
        what: ceoloide/mounting_hole_npth
        where: screw_tl
      top_right_hole:
        what: ceoloide/mounting_hole_npth
        where: screw_tr
      bottom_left_hole:
        what: ceoloide/mounting_hole_npth
        where: screw_bl
      bottom_middle_hole:
        what: ceoloide/mounting_hole_npth
        where: screw_bm
      bottom_right_hole:
        what: ceoloide/mounting_hole_npth
        where: screw_br
      ground_plane:
        what: ceoloide/utility_filled_zone
        params:
          remove_islands: always
cases:
  silicone_base:
    - name: base
      extrude: 1
  cork_base:
    - name: base
      extrude: 1.8
      shift: [0, 0, 1]
  pcb:
    - name: left_board
      extrude: 1.6
      shift: [0, 0, 1 + 1.8]
  gasket:
    - name: switch_plate
      extrude: 1
      shift: [0, 0, 1 + 1.8 + 1.6]
  switch_plate:
    - name: switch_plate
      extrude: 1.2
      shift: [0, 0, 1 + 1.8 + 1.6 + 1]
  _case_skirt:
    - name: base
      shift: [0, 0, 1]
      extrude: 1.8 + 1.6 + 1.2
  _case_upper:
    - name: base
      shift: [0, 0, 1 + 1.8 + 1.6 + 1.2]
      extrude: 4.5
  case:
    - what: case
      name: _case_skirt
    - what: case
      name: _case_upper