name: Build
on:
  workflow_dispatch:
  push:

# Borrowed with humility from https://github.com/ceoloide/corney-island/blob/main/.github/workflows/build.yaml

jobs:
  generate:
    name: Generate
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Docker cache
        uses: ScribeMD/docker-cache@0.3.7
        with:
          key: docker-${{ runner.os }}

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          # Should stay in sync with .tool-versions
          node-version: 20.17.0
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Generate unrouted PCBs with Ergogen (definition in Makefile)
        run: make build

      - name: Run Kibot to generate images, gerbers for the unrouted board
        uses: ./.github/actions/kibot
        with:
          boards: left
          config: default

      # TODO: Export DSN file for freerouting
      # TODO: Autoroute PCB
      # TODO: Import SES
      # TODO: Run Kibot to generate images, gerbers for the autorouted board

      - name: Publish output
        uses: actions/upload-artifact@v4
        with:
          name: build
          # TODO: Include cases
          path: |
            gerbers
            images
            outlines
            pcbs

      - name: Setup Pages
        if: github.ref == 'refs/heads/main'
        uses: actions/configure-pages@v3

      - name: Upload images
        if: github.ref == 'refs/heads/main'
        uses: actions/upload-pages-artifact@v1
        with:
          path: "images"

  render-image:
    name: render-image
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Render pcb image
        uses: linalinn/kicad-render@main
        with:
          pcb_file: pcbs/left.kicad_pcb
          output_path: ${{ github.workspace }}/images
        
      - name: Setup Pages
        if: github.ref == 'refs/heads/main'
        uses: actions/configure-pages@v3

      - name: Upload Artifact
        if: github.ref == 'refs/heads/main'
        uses: actions/upload-pages-artifact@v1
        with:
          path: "images"

  deploy-pages:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: [generate, render-image]
      
    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
